parameters: {}
environment: {}
packages:
    - name: telnyx
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: send_code
          binary: false
          main: "entry_point"
          runtime: python:3.11
          web: true
          webSecure: false
          environment:
            DEFAULT_VERIFY_PROFILE_ID: "${DEFAULT_VERIFY_PROFILE_ID}"
            TELNYX_API_KEY: "${TELNYX_API_KEY}"
          limits:
            timeout: 8000
        - name: submit_code
          binary: false
          main: "entry_point"
          runtime: python:3.11
          web: true
          webSecure: false
          environment: {}
          limits:
            timeout: 8000
