parameters: {}
environment: {}
packages:
    - name: verify
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: request_code
          binary: false
          main: "main"
          runtime: python:3.11
          web: true
          webSecure: false
          environment:
            DEFAULT_VERIFY_PROFILE_ID: "${DEFAULT_VERIFY_PROFILE_ID}"
            TELNYX_API_KEY: "${TELNYX_API_KEY}"
          limits:
            timeout: 10000
        - name: verify_code
          binary: false
          main: "main"
          runtime: python:3.11
          web: true
          webSecure: false
          environment:
            TELNYX_API_KEY: "${TELNYX_API_KEY}"
          limits:
            timeout: 10000
