parameters: {}
environment:
  TELNYX_API_KEY: "${TELNYX_API_KEY}"
  TELNYX_BASE_URL: "${TELNYX_BASE_URL}"
packages:
    - name: verify
      shared: false
      environment: {}
      functions:
        - name: request_code
          binary: false
          main: "main"
          runtime: python:3.11
          web: raw
          webSecure: false
          environment:
            DEFAULT_VERIFY_PROFILE_ID: "${DEFAULT_VERIFY_PROFILE_ID}"
          limits:
            timeout: 10000
        - name: verify_code
          binary: false
          main: "main"
          runtime: python:3.11
          web: raw
          webSecure: false
          limits:
            timeout: 10000
    - name: messages
      shared: false
      environment: {}
      functions:
        - name: send_message
          binary: false
          main: "main"
          runtime: python:3.11
          web: raw
          webSecure: false
          limits:
            timeout: 10000
        - name: receive_message
          binary: false
          main: "main"
          runtime: python:3.11
          web: raw
          webSecure: false
          limits:
            timeout: 10000
